In [ ]:
import pandas as pd
df=pd.read_csv('C:/Users/user/Documents/Python Scripts/ipldata_pd/matches.csv')
print(df.head())
print(len(df))



In [ ]:
df.win_by_runs.max()


In [ ]:
df.win_by_runs

In [ ]:
df.win_by_runs.idmax()

In [ ]:
df.iloc[df.win_by_runs.max()]

In [ ]:
df.iloc[df.win_by_runs.max()].winner

In [ ]:
df.iloc[df.win_by_wickets.idmax()]

In [ ]:
df.iloc[df.win_by_wickets.idxmax()]

In [ ]:
df.iloc[df.win_by_wickets.idxmax()].winner

In [ ]:
df.win_by_runs

In [ ]:
df.win_by_runs>0

In [ ]:
df[df.win_by_runs>0]

In [ ]:
df[df.win_by_runs>0].win_by_runs

In [ ]:
df[df.win_by_runs>0].win_by_runs.min

In [ ]:
df[df.win_by_runs>0].win_by_runs.min()

In [ ]:
df[df.win_by_runs>0].win_by_runs.idxmin()

In [ ]:
df[df[df.win_by_runs>0].win_by_runs.idxmin()]

In [ ]:
df.iloc[df[df.win_by_runs>0].win_by_runs.idxmin()]

In [ ]:
df.iloc[df[df.win_by_runs>0].win_by_runs.idxmin()].winner

In [ ]:
df.win_by_runs==1

In [ ]:
df[df.win_by_runs==1]

In [ ]:
df[df.win_by_runs==1].shape

In [ ]:
df.season

In [ ]:
df.season.value_counts()

In [ ]:
df.season.value_counts().max()

In [ ]:
df.season.value_counts().idxmax()

In [ ]:
df.winner.value_counts().idxmax()

In [ ]:
df.winner

In [ ]:
df.winner==df.toss_winner

In [ ]:
df[df.winner==df.toss_winner]

In [ ]:
len(df[df.winner==df.toss_winner])/len(df)

# SUPERVISED LEARNING:-
    -Regression
        -linear regression
        generates best possible linear relationship between input and output
        
    -Classification
        
    

    unsupervised
    reinforcement

In [ ]:
import numpy as np
X=np.array([3,4.4,6.5,8,8.6])     #features
Y=np.array([3.2,5.3,6,7.8,8.6])   #label

In [ ]:
import matplotlib.pyplot as plt
plt.plot(X,Y)
plt.scatter(X,Y)
plt.show()



In [ ]:
X_mean=X.mean()
Y_mean=Y.mean()

print(X_mean)
print(Y_mean)

In [ ]:
num=0
den=0
for i in range(len(X)):
    num+=(X[i]-X_mean)*(Y[i]-Y_mean)
    den+=(X[i]-X_mean)*(X[i]-X_mean)
m=num/den
print(m)
c=Y_mean-m*X_mean
print(c)


In [ ]:
x=np.linspace(X.min(),X.max())

y=m*x+c

plt.scatter(X,Y)
plt.plot(x,y)
plt.show()

In [ ]:
# download dataset: https://we.tl/t-yd0qj9nZI3

In [ ]:
import pandas as pd
data=pd.read_csv('C:/Users/user/Documents/Python Scripts/Advertising.csv')

In [ ]:
data.head()

In [ ]:
data.shape

In [ ]:
X=data.TV
Y=data.sales

In [ ]:
type(X)

In [ ]:
X[0]

In [ ]:
'''if X[0] is not accessible then
change the code from
X=data.TV to
X=data.TV.values using numpy'''

data.TV.values[0]
#Y=data.sales.values

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(X,Y)
plt.plot(X,Y)
plt.show()

In [ ]:
X_mean=X.mean()
Y_mean=Y.mean()

print(X_mean)
print(Y_mean)

In [ ]:
num=0
den=0
for i in range(len(X)):
    num+=(X[i]-X_mean)*(Y[i]-Y_mean)
    den+=(X[i]-X_mean)*(X[i]-X_mean)
m=num/den
print(m)
c=Y_mean-m*X_mean
print(c)


In [ ]:
import numpy as np

x=np.linspace(X.min(),X.max())

y=m*x+c

import matplotlib.pyplot as plt

plt.scatter(X,Y)
plt.plot(x,y,color='red')
plt.show()

In [ ]:
# Error Evaluation:-

k=m*X[0]+c
print(k)


print(Y[0]-k)

In [ ]:

'''
# Mean Squared Error:-

print((Y[0]-k)**2)

# Root Mean Squared Error:-

print(sqrt((Y[0]-k)**2))
'''



In [ ]:
X=data.TV.values
Y=data.sales.values

In [ ]:
X=X.reshape(-1,1)
Y=Y.reshape(-1,1)

In [ ]:
# Mean Absolute Error:-

from sklearn.linear_model import LinearRegression
lin=LinearRegression()


In [ ]:
#Divide X and Y into two parts:- Training Set, Testing Set

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

In [ ]:
print(X.shape)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)


In [ ]:
lin.fit(xtrain,ytrain)
#lin.fit(X,Y)

In [ ]:
lin.intercept_

In [ ]:
lin.coef_

In [ ]:
lin.predict([[56]])

In [ ]:
import numpy as np

x=np.linspace(X.min(),X.max())

y=m*x+c

import matplotlib.pyplot as plt

plt.scatter(X,Y)
plt.plot(x,y,color='red')
plt.scatter(xtest,lin.predict(xtest),color='red')
plt.show()

In [ ]:
pred=lin.predict(xtest)

In [ ]:
#Mean Absolute Error

from sklearn import metrics
metrics.mean_absolute_error(ytest,pred)

In [ ]:
np.concatenate((pred,ytest),axis=1)

'''Make a prediction model using two variable from dataset as independant variable together- TV & Radio
Use Sales as independant variable or label
Calculate the error generated'''

In [ ]:
import pandas as pd
data=pd.read_csv('C:/Users/user/Documents/Python Scripts/Advertising.csv')

In [ ]:
X=data[['TV','radio']].values
Y=data[['sales']].values

In [ ]:
#X=X.reshape(-1,1)
#Y=Y.reshape(-1,1)

In [ ]:
# Mean Absolute Error:-

from sklearn.linear_model import LinearRegression
lin=LinearRegression()

In [ ]:
#Divide X and Y into two parts:- Training Set, Testing Set

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

In [ ]:
lin.fit(xtrain,ytrain)

In [ ]:
lin.coef_

In [ ]:
pred=lin.predict(xtest)
#print(pred)

print(lin.predict([[45,89]]))


In [ ]:
#Mean Absolute Error

from sklearn import metrics
metrics.mean_absolute_error(ytest,pred)

In [ ]:
np.concatenate((pred,ytest),axis=1)

In [ ]:
X_mean=(X[0].mean()+X[1].mean())/2
Y_mean=Y.mean()

In [ ]:
num=0
den=0
for i in range(len(X)):
    num+=(X[i]-X_mean)*(Y[i]-Y_mean)
    den+=(X[i]-X_mean)*(X[i]-X_mean)
m=num/den
c=Y_mean-m*X_mean

In [ ]:
import numpy as np

x=np.linspace(X.min(),X.max())

y=m*x+c


In [ ]:
import matplotlib.pyplot as plt

plt.scatter(X,Y)
plt.plot(x,y,color='red')
plt.scatter(xtest,pred,color='red')
plt.show()

# Polynomial Regression

Equation of Polynomial Line:- Y=a + bx + cx^2

In [ ]:
import numpy as np
X=np.array([3,4.4,6.5,8,8.6])     #features
Y=np.array([3.2,5.3,6,7.8,8.6])   #label

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pol=PolynomialFeatures(degree=4)    #increase degree to get a line that touches more or less all the points
X_pol=pol.fit_transform(X.reshape(-1,1))


In [ ]:
#X_pol

In [ ]:
from sklearn.linear_model import LinearRegression
linp=LinearRegression()
linp.fit(X_pol,Y)

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(X,Y)
plt.plot(X,linp.predict(X_pol),color='red')
#plt.scatter(xtest,pred,color='red')
plt.show()

'''Use 'lotsize' as feature and 'price' as label for the algorithm.
Use Polynomial Regression to:-
    1. Plot the best fit line over data values
    2. Calculate best possible degree value
    3. Minimum possible error value
    '''
    

In [ ]:
import pandas as pd
housing=pd.read_csv('C:/Users/user/Documents/Python Scripts/Housing_Data.csv')

In [ ]:
housing.head()

In [ ]:
import numpy as np
X=housing[['lotsize']].values     #features
Y=housing[['price']].values       #label

In [ ]:
#Divide X and Y into two parts:- Training Set, Testing Set

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y)#,test_size=0.2)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pol=PolynomialFeatures(degree=7)               #increase degree to get best fit line


xtrain_pol=pol.fit_transform(xtrain)


In [ ]:
from sklearn.linear_model import LinearRegression
linp=LinearRegression()
linp.fit(xtrain_pol,ytrain)

xtest_pol=pol.fit_transform(xtest)
pred=linp.predict(xtest_pol)


from sklearn import metrics
metrics.mean_absolute_error(ytest,pred)



In [ ]:
error=[]
for i in range(1,10):
    pol=PolynomialFeatures(degree=i)    
    xtrain_pol=pol.fit_transform(xtrain)
    
    #training
    linp=LinearRegression()
    linp.fit(xtrain_pol,ytrain)

    #prediction
    xtest_pol=pol.fit_transform(xtest)
    pred=linp.predict(xtest_pol)
    
    error.append(metrics.mean_absolute_error(ytest,pred))
    
    

plt.plot(np.arange(1,10),error)
plt.show()

In [ ]:
xtest_new=np.linspace(xtest.min(),xtest.max())
xtest_new_pol=pol.fit_transform(xtest_new.reshape(-1,1))

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(X,Y)

plt.plot(xtest,linp.predict(xtest_pol),color='red')


#plt.plot(X,Y,color='black')
#plt.plot(np.linspace(X.min(),X.max()),linp.predict(np.linspace(X.min(),X.max())),color='red')
#plt.scatter(xtest,pred,color='red')
plt.show()

# Classification Task

In [ ]:
import pandas as pd
iris=pd.read_csv('C:/Users/user/Documents/Python Scripts/Iris.csv',index_col=0)

In [ ]:
iris.head(3)

In [ ]:
iris.dtypes

In [ ]:
iris['mapped']=iris.Species.map({'Iris-setosa':0, 
                                 'Iris-versicolor':1, 
                                 'Iris-virginica':2})

In [ ]:
iris[['Species','mapped']]

In [ ]:
import numpy as np
X=iris.drop(['Species','mapped'],axis=1)   #features
Y=iris['mapped']                          #label

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.30)

In [ ]:
#KNN, SVM, DTC, Random forest

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(xtrain,ytrain)

In [ ]:
knn.predict([[4,5,3,6]])

In [ ]:
pred=knn.predict(xtest)

In [ ]:
pred[0]

In [ ]:
ytest.values[0]

In [ ]:
count=0
for i in range(len(xtest)):
    if pred[i]==ytest.values[i]:
        count+=1
        
#Aaccuracy
print(count/len(xtest))

In [ ]:
knn.score(xtest,ytest)

In [ ]:
ytest.values[1]

In [ ]:
xtest.shape

In [ ]:
acc=[]
for i in range(1,15):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(xtrain,ytrain)
    acc.append(knn.score(xtest,ytest))

import numpy as np
import matplotlib.pyplot as plt
#plt.scatter(X,Y)
plt.plot(np.arange(1,15),acc,color='red')
plt.show()

In [ ]:
name=np.array(['setosa','versicolor','virginica'])
p=knn.predict([[1.3,0.2,2.2,1.5],[2.3,2,5,6],[9,8,7.7,8.7]])

In [ ]:
type(p)

In [ ]:
print(name[p])

# '''Use Bigmart dataset to create prediction model for predicting sales based upon different features'''

In [ ]:
import pandas as pd
mart=pd.read_csv('C:/Users/user/Documents/Python Scripts/Bigmart/Big_mart_train.csv')#,index_col=0)
mart.head()

In [ ]:
mart.Item_Weight

In [ ]:
#checking for null values
#if values are >0 then there are null
mart.isnull().sum()

# Dealing Missing Values

In [ ]:
mean_weight=mart.Item_Weight.mean()
print(mean_weight)

#filling the null values with the mean

#mart.Item_Weight=mart.Item_Weight.fillna(mean_weight)
#or
mart.Item_Weight.fillna(mean_weight, inplace=True)

In [ ]:
mart.isnull().sum()

In [ ]:
mart.Outlet_Size

In [ ]:
mart.Outlet_Size.value_counts()

In [ ]:
mean_size=mart.Outlet_Size.value_counts().idxmax()
print(mean_size)

In [ ]:
mart.Outlet_Size.fillna(mean_size, inplace=True)

In [ ]:
mart.isnull().sum()

In [ ]:
mart.head()

# Dealing with useless column

In [ ]:
#Drop all useless columns
mart.drop(['Item_Identifier','Outlet_Identifier'], axis=1, inplace=True)

In [ ]:
mart.head()

In [ ]:
#Train Test Split

from sklearn.model_selection import train_test_split
train,test=train_test_split(mart)

In [ ]:
mart.shape

In [ ]:
train.shape

In [ ]:
test.shape

In [ ]:
xtrain=train.drop('Item_Outlet_Sales',axis=1)
ytrain=train['Item_Outlet_Sales']

In [ ]:
xtest=test.drop('Item_Outlet_Sales',axis=1)
ytest=test['Item_Outlet_Sales']

In [ ]:
xtrain.dtypes

In [ ]:
import pandas as pd

pd.get_dummies(xtrain).head(3)

In [ ]:
xtrain=pd.get_dummies(xtrain)

In [ ]:
xtrain.shape

'''Make Prediction model after all preprocessings on data set
using a regression based algorithm and
calculate error'''

In [ ]:
# K-Neighbors Regressor
from sklearn.neighbors import KNeighborsRegressor
knr=KNeighborsRegressor(n_neighbors=5)


In [ ]:
knr.fit(xtrain,ytrain)

In [ ]:
xtest=pd.get_dummies(xtest)

In [ ]:
ypred=knr.predict(xtest)

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest,ypred)

In [ ]:
from sklearn.metrics import mean_squared_error


error=[]
for i in range(1,25):
    knr=KNeighborsRegressor(n_neighbors=i)
    knr.fit(xtrain,ytrain)
    pred=knr.predict(xtest)
    error.append(mean_squared_error(ytest,pred))

import numpy as np
import matplotlib.pyplot as plt
#plt.scatter(X,Y)
plt.plot(np.arange(1,25),error,color='red')
plt.show()

In [ ]:
my_plot=pd.DataFrame(error)
get_ipython().magic('matplotlib inline')
my_plot.plot()
plt.show()

In [ ]:
import pandas as pd
mart_test=pd.read_csv('C:/Users/user/Documents/Python Scripts/Bigmart/Big_Mart_Test.csv')
mart_test.head()

In [ ]:
mart_test.drop(['Item_Identifier','Outlet_Identifier'], axis=1, inplace=True)

In [ ]:
mart_test.isnull().sum()

In [ ]:
mean_weight=mart_test.Item_Weight.mean()
print(mean_weight)

#filling the null values with the mean

#mart.Item_Weight=mart.Item_Weight.fillna(mean_weight)
#or
mart_test.Item_Weight.fillna(mean_weight, inplace=True)

In [ ]:
mart_test.isnull().sum()

In [ ]:
mean_size=mart_test.Outlet_Size.value_counts().idxmax()
print(mean_size)

In [ ]:
mart_test.Outlet_Size.fillna(mean_size, inplace=True)

In [ ]:
mart_test.isnull().sum()

In [ ]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(mart_test)

# supervised
train machine
2*2=4
2*3=6

machine generates
2*8=18

error evaluation
18-16=2

optimization
2*10


# model for image recognition-
    fruits identification
apple-<features>
mango-<features>


slope of line which passes through mean of all points=sum((x-x_mean)(y-y_mean))/sum((x-x_mean)^2)



# unsupervised


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df=pd.DataFrame({
    'x':[12,20,28,18,29,33,24,45,52,51,53,55,54,65,61,67,69,72,76],
    'y':[39,36,30,52,54,46,55,59,63,70,66,63,58,23,14,8,19,7,78]
})

In [ ]:
df

In [ ]:
plt.scatter(df.x,df.y)
#plt.plot(df.x,df.y,color='red')
plt.show()

In [ ]:
centroids={i+1 : [np.random.randint(0,80),
                  np.random.randint(0,80)]
           for i in range(3)}

In [ ]:
centroids

In [ ]:
plt.scatter(df['x'],df.y)

colmap={1:'r', 2:'g', 3:'b'}
for i in centroids.keys():
    plt.scatter(*centroids[i], color=colmap[i])

#plt.plot(df.x,df.y,color='r')
plt.show()

In [ ]:
colmap={1:'r', 2:'g', 3:'b'}

#Assignment Stage
def assignment(df, centroids):
    for i in centroids.keys():
        #sqrt((x1-x2)^2+(y1-y2)^2)
        #Euclidean Distance
        df['distance_from_{}'.format(i)]=np.sqrt((df['x']-centroids[i][0]) **2 + 
                                                 (df['y']-centroids[i][1]) **2)
        
        df['closest']=df.loc[:,'distance_from_1':'distance_from_3'].idxmin(axis=1)
        df['closest']=df['closest'].map(lambda x: int(x.lstrip('distance_from_')))
        df['color']=df['closest'].map(lambda x: colmap[x])
        
    return df        
        
df=assignment(df, centroids)
df.head()

In [ ]:
plt.scatter(df['x'],df.y,color=df.color,edgecolor='k')

colmap={1:'r', 2:'g', 3:'b'}
for i in centroids.keys():
    plt.scatter(*centroids[i], color=colmap[i])

plt.show()

In [ ]:
#Update Stage
import copy
old_centroids=copy.deepcopy(centroids)


In [ ]:
def update(k):
    for i in centroids.keys():
        centroids[i][0]=np.mean(df[df['closest']==i]['x'])
        centroids[i][1]=np.mean(df[df['closest']==i]['y'])
        
        
    return k

centroids=update(centroids)

In [ ]:
print(old_centroids)
print(centroids)

In [ ]:
#Repeat Assignment Stage
df=assignment(df, centroids)

centroids=update(centroids)
df=assignment(df, centroids)

#centroids=update(centroids)
#df=assignment(df, centroids)


In [ ]:
print(centroids)

In [ ]:
plt.scatter(df['x'],df.y,color=df.color,edgecolor='k')

colmap={1:'r', 2:'g', 3:'b'}
for i in centroids.keys():
    plt.scatter(*centroids[i], color=colmap[i])

plt.show()

In [ ]:
#By KMeans Algorithm

df=pd.DataFrame({
    'x':[12,20,28,18,29,33,24,45,52,51,53,55,54,65,61,67,69,72,76],
    'y':[39,36,30,52,54,46,55,59,63,70,66,63,58,23,14,8,19,7,78]
})

In [ ]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=3)#, max_iter=200)
kmeans.fit(df)

In [ ]:
centroids=kmeans.cluster_centers_
centroids

In [ ]:
labels=kmeans.predict(df)
labels

In [ ]:
colmap={1:'r', 2:'g', 3:'b'}

colors=map(lambda x:colmap[x+1], labels)
colors1=list(colors)

plt.scatter(df['x'],df.y,color=colors1,edgecolor='k')

for idx,centroid in enumerate(centroids):
    plt.scatter(*centroid, color=colmap[idx+1])

plt.show()

In [ ]:
cost=[]
for i in range(1,11):
    KM=KMeans(n_clusters=i, max_iter=400)
    KM.fit(df)
    
    cost.append(KM.inertia_)


In [ ]:
plt.plot(np.arange(1,11), np.array(cost))
plt.xlabel('Value of K')
plt.ylabel('Squared Error (cost)')
plt.show()


# Hand Written Digits

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#%matplotlib inline

In [ ]:
digit=pd.read_csv('C:/Users/user/Documents/Python Scripts/digit-recognizer/train.csv')

In [ ]:
digit.head()

In [ ]:
digit.shape

In [ ]:
#784 - Feature + 1 - Label

f=digit.drop('label',axis=1).values
l=digit['label'].values


In [ ]:
print(l[6])
d=f[6]
d.shape=(28,28)
plt.imshow(d)
plt.show()

In [ ]:
test_digit=pd.read_csv('C:/Users/user/Documents/Python Scripts/digit-recognizer/test.csv')

In [ ]:
t=test_digit.values

In [ ]:
d=t[6]
d.shape=(28,28)
plt.imshow(d)
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(f,l,test_size=0.2)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(xtrain,ytrain)

In [ ]:
knn.score(xtest,ytest)

In [ ]:
t[0].shape

In [ ]:
p=knn.predict(t)

In [ ]:
print(p[6])
d=f[6]
d.shape=(28,28)
plt.imshow(d)
plt.show()

# SVM Algo

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
iris=load_iris()

In [ ]:
dir(iris)

In [ ]:
iris.feature_names

In [ ]:
iris.target_names

In [ ]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [ ]:
df.head()

In [ ]:
df['target']=iris.target

In [ ]:
df.head()

In [ ]:
iris.target_names[2]

In [ ]:
df['target_names']=df.target.apply(lambda x: iris.target_names[x])

In [ ]:
df.head()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df0=df[:50]       #Setosa
df1=df[50:100]    #Versicolor
df2=df[100:]      #Virginica


In [ ]:
plt.xlabel('sepal length')
plt.ylabel('sepal width')

plt.scatter(df0['sepal length (cm)'],
            df0['sepal width (cm)'],
            color='green',
            marker='+')

plt.scatter(df1['sepal length (cm)'],
            df1['sepal width (cm)'],
            color='red',
            marker='*')

plt.show()

In [ ]:
X=df.drop(['target','target_names'],axis=1)
Y=df.target

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
from sklearn.svm import SVC
model=SVC()

In [ ]:
model.fit(X_train,Y_train)

In [ ]:
model.score(X_test,Y_test)

In [ ]:
model_c=SVC(C=7)
model_c.fit(X_train,Y_train)

In [ ]:
model_c.score(X_test,Y_test)

In [ ]:
# DTC / Legendary Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(X_train,Y_train)

In [ ]:
clf.score(X_test,Y_test)

In [ ]:
# Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)

In [ ]:
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

'''Make model for Hand Written Digit Recognizer using DTC and Random Forest seperately and Compare the Performance. Make Prediction for any one of digit from test.csv file'''

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
digit=pd.read_csv('C:/Users/user/Documents/Python Scripts/digit-recognizer/train.csv')

In [ ]:
f=digit.drop('label',axis=1).values
l=digit['label'].values

In [ ]:
print(l[6])
d=f[6]
d.shape=(28,28)
plt.imshow(d)
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(f,l,test_size=0.2)

In [ ]:
#DTC

from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(X_train,Y_train)

In [ ]:
clf.score(X_test,Y_test)

In [ ]:
#RandomForest

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)

In [ ]:
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

In [ ]:
Y_pred=model.predict(X_test)

In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)

In [ ]:
cm

In [ ]:
import seaborn as sns
sns.heatmap(cm, annot=True, fmt='.4g', cmap='RdGy')
plt.xlabel('Predicted')
plt.ylabel('Truth')
plt.show()

# Image Feature Extraction
# Open CV
Open anaconda prompt(admin mode) ->  

conda install py-opencv=3.4.2.
conda install py-opencv
conda install opencv
conda install -c conda-forge opencv

# for environment creation,
conda create -n myenv opencv
activate myenv
conda install notebook

https://anaconda.org/anaconda/py-opencv


In [ ]:
import cv2

In [ ]:
train_dir='C:/Users/user/Documents/Python Scripts/all1/train'

In [ ]:
a='cat.1.jpg'
a.split('.')

In [ ]:
a.split('.')[0]

In [ ]:
def level(img):
    l=img.split('.')[0]
    if l=='cat':
        return 0
    elif l=='dog':
        return 1


In [ ]:
level('dog.1.jpg')

In [ ]:
level(a)

In [ ]:
'''conda install tqdm
or
pip install tqdm'''

import os
from tqdm import tqdm

In [ ]:
training_data=[]
def train_data():
    for img in tqdm(os.listdir(train_dir)):
        path=os.path.join(train_dir,img)
        feature=cv2.imread(path,0)
        feature=cv2.resize(feature,(50,50))
        training_data.append(feature)
    return training_data


In [ ]:
train=train_data()

In [ ]:
import numpy as np
np.array(train).shape

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(train[0])
plt.show()

In [ ]:
levels=[]
for img in tqdm(os.listdir(train_dir)):
    k=level(img)
    levels.append(k)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(train,levels)

In [ ]:
'''activate myenv
conda install scikit-learn'''

In [ ]:
train=np.array(train).reshape(25000,2500)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(train,levels)

In [ ]:
train

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=300)

In [ ]:
model.fit(xtrain,ytrain)
model.score(xtest,ytest)

In [ ]:
test_file='C:/Users/user/Documents/Python Scripts/all1/test'

In [ ]:
testing_data=[]
def test_data():
    for img in tqdm(os.listdir(test_file)):
        path=os.path.join(test_file,img)
        feature=cv2.imread(path,0)
        feature=cv2.resize(feature,(50,50))
        testing_data.append(feature)
    return testing_data


In [ ]:
test_features=test_data()

In [ ]:
test_feature=np.array(test_features)

In [ ]:
plt.imshow(test_feature[700])
plt.show()

In [ ]:
xtrain.shape

In [ ]:
t_f=test_feature.reshape(12500,2500)

In [ ]:
model.predict(t_f[[8000]])

In [ ]:
print(model.predict(t_f[[8000]]))

plt.imshow(test_feature[8000])
plt.show()

In [ ]:
'''activate myenv
conda install tensorflow'''

# Neural Network

In [ ]:
import tensorflow as tf
tf.__version__

In [ ]:
mnist=tf.keras.datasets.mnist

In [ ]:
(xtrain,ytrain),(xtest,ytest)=mnist.load_data()

In [ ]:
xtrain[0]

In [ ]:
xtrain=tf.keras.utils.normalize(xtrain)
xtest=tf.keras.utils.normalize(xtest)

In [ ]:
xtrain[0]

In [ ]:
d=xtrain[0]

import matplotlib.pyplot as plt
plt.imshow(d)
plt.show()

In [ ]:
model=tf.keras.models.Sequential()

#Input Layer
model.add(tf.keras.layers.Flatten())

#Hidden Layer
model.add(tf.keras.layers.Dense(128, activation='relu'))

#Hidden Layer
model.add(tf.keras.layers.Dense(256, activation='relu'))

#Hidden Layer
model.add(tf.keras.layers.Dense(128, activation='relu'))

#Final Layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

'''there are total 8 activation functions
-Threshold or Binary step
-Sigmoid or Logistic
-tanh or Hyperbolic tangent
-ArcTan
-ReLU
-Leaky ReLU
-SoftMax'''

In [ ]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [ ]:
model.fit(xtrain,ytrain,epochs=5)

In [ ]:
pred=model.predict(xtest)

In [ ]:
ytest[50]

In [ ]:
pred[50]

In [ ]:
import numpy as np
np.argmax(pred[50])

'''Use NN to predict Cat and Dog'''

In [ ]:
import cv2
import numpy as np
import os
from random import shuffle

In [ ]:
Train_dir='C:/Users/user/Documents/Python Scripts/all1/train'
Test_dir='C:/Users/user/Documents/Python Scripts/all1/test'

In [ ]:
#Extract label:-
def label_img(img):
    l=img.split('.')[0]
    if l=='cat':
        return 0
    elif l=='dog':
        return 1
    

In [ ]:
from tqdm import tqdm

In [ ]:
label=[]
for img in tqdm(os.listdir(Train_dir)):
    label.append(label_img(img))

In [ ]:
#label
features=[]
for img in tqdm(os.listdir(Train_dir)):
    path=os.path.join(Train_dir,img)
    f=cv2.imread(path,0)
    f=cv2.resize(f,(100,100))
    features.append(f)


In [ ]:
features=np.array(features)

In [ ]:
label=np.array(label)

In [ ]:
import tensorflow as tf

In [ ]:
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(1024, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(1024, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

In [ ]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [ ]:
features.shape

In [ ]:
model.fit(features, label, epochs=3)

In [ ]:
pred=model.predict(xtest)[0]

In [ ]:
ytest[50]

In [ ]:
import numpy as np
np.argmax(pred[50])

In [ ]:
plt.imshow(features[8000])
plt.show()

In [ ]:
features.shape

In [ ]:
xtrain.shape

In [ ]:
xtest.shape

In [ ]:
print(model.predict(features.reshape(25000,2500)[[8000]]))

In [ ]:
features.reshape(-1,2500)[[8000]].shape

# CNN - Convolution Neural Network

In [1]:
import cv2
import numpy as np
import os
from random import shuffle
from tqdm import tqdm

In [2]:
TRAIN_DIR='C:/Users/user/Documents/Python Scripts/all1/train'
TEST_DIR='C:/Users/user/Documents/Python Scripts/all1/test'

In [3]:
def label_img(img):
    word_label=img.split('.')[0]
    if word_label=='cat': return [1,0]
    elif word_label=='dog': return [0,1]

In [4]:
def create_train_data():
    training_data = []
    for img in tqdm(os.listdir(TRAIN_DIR)):
        label = label_img(img)
        path = os.path.join(TRAIN_DIR,img)
        img = cv2.resize(cv2.imread(path,0),(50,50))
        training_data.append([np.array(img),np.array(label)])
        
    shuffle(training_data)
    np.save('train_data.npy', training_data)
    return training_data

In [5]:
train_data = create_train_data()

100%|█████████████████████████████████████████████| 25000/25000 [02:11<00:00, 190.45it/s]


In [6]:
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

model = input_data(shape=[None, 50, 50, 1], name='input')

#Conv Layer
model = conv_2d(model, 46, 5, activation='relu')
model = max_pool_2d(model, 5)

#Conv Layer
model = conv_2d(model, 42, 5, activation='relu')
model = max_pool_2d(model, 5)

#Conv Layer
model = conv_2d(model, 38, 5, activation='relu')
model = max_pool_2d(model, 5)

#Conv Layer
model = conv_2d(model, 34, 5, activation='relu')
model = max_pool_2d(model, 5)


#Fully Connected
model = fully_connected(model, 1024, activation='relu')
model = dropout(model, 0.7)

model = fully_connected(model, 2, activation='softmax')

model = regression(model, optimizer='adam', learning_rate=0.0003, loss='categorical_crossentropy', name='outputs')

cnnmodel = tflearn.DNN(model)

curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
Use tf.cast instead.


In [7]:
train = train_data[:-500]
test = train_data[-500:]

In [8]:
X = np.array([i[0] for i in train]).reshape(-1, 50, 50, 1)
Y = [i[1] for i in train]

test_x = np.array([i[0] for i in test]).reshape(-1, 50, 50, 1)
test_y = [i[1] for i in test]

In [9]:
cnnmodel.fit({'input': X}, {'outputs': Y}, n_epoch=5, 
             validation_set=({'input': test_x}, {'outputs': test_y}),
             show_metric=True)

Training Step: 1914  | total loss: 0.42028 | time: 169.532s
| Adam | epoch: 005 | loss: 0.42028 - acc: 0.8061 -- iter: 24448/24500
Training Step: 1915  | total loss: 0.42301 | time: 171.700s
| Adam | epoch: 005 | loss: 0.42301 - acc: 0.8067 | val_loss: 0.48109 - val_acc: 0.7760 -- iter: 24500/24500
--


In [ ]:
'''Make Predictions over test directory images'''

# Face Detect

In [1]:
import cv2
import sys

In [2]:
imagepath = 'C:/Users/user/Documents/Python Scripts/faces.jpg'
cascpath = 'C:/Users/user/Documents/Python Scripts/haarcascade_frontalface_default.xml'

In [3]:
faceclassifier = cv2.CascadeClassifier(cascpath)

In [6]:
image = cv2.imread(imagepath)
#image = cv2.resize(image, (500, 500))

In [7]:
faces = faceclassifier.detectMultiScale(image,
                                        minSize = (30, 30),
                                        scaleFactor = 1.1,
                                        minNeighbors = 5,
                                        flags = cv2.CASCADE_SCALE_IMAGE)

In [8]:
print("No. of Faces ", len(faces))

No. of Faces  4


In [9]:
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow(str(len(faces)) + " Faces found", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Image Detection from Webcam Capture

In [4]:
from time import sleep
wcam = cv2.VideoCapture(0)
State, Frame = wcam.read()
print(State)
print(Frame)
sleep(2)
cv2.imshow('my image', Frame)
cv2.waitKey(0)
wcam.release()
cv2.destroyAllWindows()

True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


'''Detect number of faces and draw squares on captured image'''

In [11]:
faces = faceclassifier.detectMultiScale(Frame,
                                        minSize = (30, 30),
                                        scaleFactor = 1.1,
                                        minNeighbors = 5,
                                        flags = cv2.CASCADE_SCALE_IMAGE)

In [ ]:
for (x, y, w, h) in faces:
    cv2.rectangle(Frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow(str(len(faces)) + " Faces found", Frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Video Capturing

In [1]:
import cv2

video = cv2.VideoCapture(0)
a=1
while True:
    a=a+1
    check, frame = video.read()
        
    key = cv2.waitKey(1)
    if key == ord('a'):
        break
    
    faces = face_cascade.detectMultiScale(frame,
                                            minSize = (30, 30),
                                            scaleFactor = 1.1,
                                            minNeighbors = 5,
                                            flags = cv2.CASCADE_SCALE_IMAGE)
    
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        
        
    
    cv2.imshow("capturing...", frame)       
        
    
print(a)
video.release()
cv2.destroyAllWindows()


645


In [17]:
eye_cascade = cv2.CascadeClassifier(r'C:/Users/user/Documents/Python Scripts/haarcascade_eye.xml')
for (x,y,w,h) in faces:
    roi_color = Frame[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_color)
    if len(eyes) == 0:
        print('no eyes!!!')             
    else:
        print('eyes!!!')
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,0,0),2)  
    print(len(eyes))
cv2.imshow("captured", Frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

no eyes!!!
0


In [ ]:
'''import cv2
from gtts import gTTS
import os
from playsound import playsound
 
 
# multiple cascades: https://github.com/Itseez/opencv/tree/master/data/haarcascades
 
#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml
face_cascade = cv2.CascadeClassifier(r'C:\Users\umang\Desktop\CV\face\haarcascade_frontalface_default.xml')
#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_eye.xml
eye_cascade = cv2.CascadeClassifier(r'C:\Users\umang\Desktop\CV\face\haarcascade_eye.xml')
 
cap = cv2.VideoCapture(0)
count = 0
while 1:
    ret, img = cap.read()
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
  #  print(len(faces))
       
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_color = img[y:y+h, x:x+w]
     #   crop_image = img[y:y+h, x:x+w]
     #   cv2.imwrite("abc/frame%d.jpg" % count, crop_image)
       
        eyes = eye_cascade.detectMultiScale(roi_color)
        if len(eyes) == 0:
            print('no eyes!!!')    
            myobj = gTTS(text='Wake Up Umang', lang='en', slow=False)
            myobj.save("C:/Users/umang/Desktop/CV/Output/welcome.mp3")
            playsound(f'E:/welcome.mp3')
           # os.system("start C:/Users/umang/Desktop/CV/Output/welcome.mp3")
           
        else:
            print('eyes!!!')
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)  
        print(len(eyes))
       
 
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
 
cap.release()
cv2.destroyAllWindows()'''